name: Nightly Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
          check-latest: true

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Perform Code Generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # - name: Generate SplashScreen
      #   run: flutter pub run flutter_native_splash:create

      # - name: Generate Launcher Icons
      #   run: flutter pub run flutter_launcher_icons -f flutter_launcher_icons.yaml

      - name: Build Android Release
        run: flutter build apk --profile

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tubesync_android_${{ github.sha }}
          path: build/app/outputs/flutter-apk/app-profile.apk
